drop table if exists products;
drop table if exists categories;

create table categories (
    id bigint generated by default as identity primary key,
    name text not null,
    slug text unique not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table products (
    id bigint generated by default as identity primary key,
    name text not null,
    description text,
    price numeric(10, 2) not null check (price >= 0),
    image_url text,
    category_id bigint references categories(id) on delete set null,
    is_bestseller boolean default false,
    stock_quantity int default 0,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

insert into categories (name, slug) values ('Dla mężczyzn', 'mezczyzni'), ('Dla kobiet', 'kobiety');

insert into products (name, description, price, image_url, category_id, is_bestseller) values ('Blue de Chanel', 'Klasyczny zapach wolności i elegancji.', 450.00, 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=500', 1, true), ('Sauvage Dior', 'Surowy, szlachetny i niezwykle trwały.', 380.50, 'https://images.unsplash.com/photo-1541643600914-78b084683601?w=500', 1, true), ('Acqua di Gio', 'Ikona świeżości inspirowana morzem.', 320.00, 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=500', 1, false), ('La Vie Est Belle', 'Najpiękniejszy zapach szczęścia dla kobiet.', 410.00, 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=500', 2, true), ('Black Opium', 'Zmysłowy miks kawy, wanilii i białych kwiatów.', 395.00, 'https://images.unsplash.com/photo-1590736704728-f4730bb30770?w=500', 2, true), ('Si Passione', 'Intensywny i bezkompromisowy zapach miłości.', 430.00, 'https://images.unsplash.com/photo-1541108564883-b91358006a15?w=500', 2, false);